name: 🚀 Deploy to Server

on:
  push:
    branches:
      - main   # se ejecuta cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /var/www/html/mvc   # 📌 cambia esta ruta a la de tu proyecto en el servidor
            git pull origin main
            # reiniciar servicio (elige el que uses)
            sudo systemctl restart apache2 || sudo systemctl restart nginx || sudo systemctl restart php8.1-fpm
          EOF
